server:
  port: 8000
resilience4j:
  circuitbreaker:
    configs:
      default:
        minimunNumberOfCalls: 5 #최소한의 요청수
        failureRateThreshold: 50 #에러비율
        waitDurationInopenState: 10s
  retry:
    configs:
      default:
        maxRetryAttempts: 2
        waitDuration: 5
        ignoreException:
          - java.util.NoSuchElementException
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
  bulkhead:
    configs:
      default:
        maxConCurrentCalls: 25
        maxWaitDuration: 0
  ratelimiter:
    configs:
      default:
        limitForPeriod: 50
        limitRefreshPeriod: 500ns
        timeoutDuration: 5s


eureka:
  instance:
    instance-id: gateway-ms-instance
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
spring:
  security:
    jwt:
      token:
        security-key: secretKey
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: [ "**" ] #??? ???
            allow-credentials: true
            add-to-simple-url-handler-mapping: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - token
              - refresh
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: come to study-share gateway service
            preLogger: true
            postLogger: true


